export const ROUTE_NAMES = [
    "Ithaca Commons - Seneca St",
    "Albany at Salvation Army",
    "Ithaca Commons - Green St",
    "State/MLK @ Stewart",
    "State/MLK @ Quarry",
    "College @ Mitchell",
    "Collegetown Crossing",
    "College @ Oak",
    "Carpenter Hall",
    "Baker Flagpole - Slope Side",
    "Milstein Hall",
    "Thurston at Balch Hall",
    "Jessup @ Triphammer",
    "Robert Purcell Community Center",
    "Jessup @ Pleasant Grove",
    "Pleasant Grove @ Hanshaw",
    "Triphammer @ Texas",
    "Triphammer @ Winthrop",
    "Triphammer at Kendal",
    "Triphammer Marketplace",
    "Cayuga Mall",
    "Graham @ Butler",
    "The Shops at Ithaca Mall",
    "Statler Hall"
  ];